services:
  server:
    build: .
    command: uv run fastapi run src/app/interface/api/main.py --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  worker:
    build: .
    command: uv run rq worker --url redis://redis:6379
