[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "jeremyarancio", email = "jeremyarancio@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.83",
    "fastapi[standard]>=0.135.2",
    "loguru>=0.7.3",
    "pydantic>=2.12.5",
    "redis>=7.4.0",
    "rq>=2.7.0",
]

[project.scripts]
workers-process = "workers_process:main"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"
